### ISSUE TITLE
Docker image for spark-2.0-preview

### ISSUE THREAD

**Issue by endriju** [spark-jobserver/spark-jobserver#693]
Hi,

the existing Docker images for spark-jobserver are really helpful, I was wondering if there are any plans to publish image for the spark-2.0-preview?

Thanks,
Ondrej

**Comment by depend** [comment]
I publish one here. https://hub.docker.com/r/depend/spark-jobserver/. I made some minor changes (CentOS, HotSpot JVM etc).

**Comment by vvsh** [comment]
@depend, I tried to use your image to run spark with mesos, but I got this exception:

`Failed to initialize context Actor[akka.tcp://JobServer@127.0.0.1:35159/user/jobManager-c8-9bd7-a607f6c68326#98780565]
java.lang.UnsatisfiedLinkError: /usr/lib/libmesos-1.0.0.so: libdb-4.7.so: cannot open shared object file: No such file or directory
at java.lang.ClassLoader$NativeLibrary.load(Native Method)
at java.lang.ClassLoader.loadLibrary0(Unknown Source)
at java.lang.ClassLoader.loadLibrary(Unknown Source)
at java.lang.Runtime.loadLibrary0(Unknown Source)
at java.lang.System.loadLibrary(Unknown Source)
at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:54)
at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:79)
at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:2487)
at org.apache.spark.SparkContext.<init>(SparkContext.scala:489)
at org.apache.spark.streaming.StreamingContext$.createNewSparkContext(StreamingContext.scala:836)
at org.apache.spark.streaming.StreamingContext.<init>(StreamingContext.scala:84)
at spark.jobserver.context.StreamingContextFactory$$anon$1.<init>(StreamingContextFactory.scala:18)
at spark.jobserver.context.StreamingContextFactory.makeContext(StreamingContextFactory.scala:18)
at spark.jobserver.context.StreamingContextFactory.makeContext(StreamingContextFactory.scala:8)
at spark.jobserver.context.SparkContextFactory$class.makeContext(SparkContextFactory.scala:63)
at spark.jobserver.context.StreamingContextFactory.makeContext(StreamingContextFactory.scala:8)
at spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:135)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
at spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)
at spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)
at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
at spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:23)
at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
at spark.jobserver.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
at akka.actor.ActorCell.invoke(ActorCell.scala:495)
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
at akka.dispatch.Mailbox.run(Mailbox.scala:224)
at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

**Comment by vvsh** [comment]
@depend, I tried to use your image to run spark on mesos, but I got this exception:

Failed to initialize context Actor[akka.tcp://JobServer@127.0.0.1:35159/user/jobManager-c8-9bd7-a607f6c68326#98780565]
java.lang.UnsatisfiedLinkError: /usr/lib/libmesos-1.0.0.so: libdb-4.7.so: cannot open shared object file: No such file or directory
at java.lang.ClassLoader$NativeLibrary.load(Native Method)
at java.lang.ClassLoader.loadLibrary0(Unknown Source)
at java.lang.ClassLoader.loadLibrary(Unknown Source)
at java.lang.Runtime.loadLibrary0(Unknown Source)
at java.lang.System.loadLibrary(Unknown Source)
at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:54)
at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:79)
at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:2487)
at org.apache.spark.SparkContext.<init>(SparkContext.scala:489)
at org.apache.spark.streaming.StreamingContext$.createNewSparkContext(StreamingContext.scala:836)
at org.apache.spark.streaming.StreamingContext.<init>(StreamingContext.scala:84)
at spark.jobserver.context.StreamingContextFactory$$anon$1.<init>(StreamingContextFactory.scala:18)
at spark.jobserver.context.StreamingContextFactory.makeContext(StreamingContextFactory.scala:18)
at spark.jobserver.context.StreamingContextFactory.makeContext(StreamingContextFactory.scala:8)
at spark.jobserver.context.SparkContextFactory$class.makeContext(SparkContextFactory.scala:63)
at spark.jobserver.context.StreamingContextFactory.makeContext(StreamingContextFactory.scala:8)
at spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:135)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
at spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)
at spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)
at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
at spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:23)
at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
at spark.jobserver.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
at akka.actor.ActorCell.invoke(ActorCell.scala:495)
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
at akka.dispatch.Mailbox.run(Mailbox.scala:224)
at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

It seems this image is not complete.

**Comment by depend** [comment]
hmm, sounds like a mesos package issue on CentOS. Let me take a look.

**Comment by depend** [comment]
I just pushed a new image with libdb-4.7 installed. I don't have mesos cluster at hand so you may have to pull and test. Let me know if it works or not.

**Comment by endriju** [comment]
@depend Thanks for sharing the images. I tried running the latest one from https://hub.docker.com/r/depend/spark-jobserver/tags/ but got an exception.

docker run -d -p 8090:8090 depend/spark-jobserver:spark-2.0-preview.mesos-1.0.0.spark-2.0.2.scala-2.11.jdk-8u112

Do I need to run the image with some parameters?

```
[2017-01-03 23:09:47,392] INFO  Remoting [] [Remoting] - Remoting started; listening on addresses :[akka.tcp://JobServer@127.0.0.1:44455]
Exception in thread "main" java.lang.NoSuchMethodError: akka.util.Helpers$.toRootLowerCase(Ljava/lang/String;)Ljava/lang/String;
	at akka.cluster.ClusterSettings.<init>(ClusterSettings.scala:41)
	at akka.cluster.Cluster.<init>(Cluster.scala:59)
	at akka.cluster.Cluster$.createExtension(Cluster.scala:34)
	at akka.cluster.Cluster$.createExtension(Cluster.scala:29)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:713)
	at akka.actor.ExtensionId$class.apply(Extension.scala:79)
	at akka.cluster.Cluster$.apply(Cluster.scala:29)
	at akka.cluster.ClusterActorRefProvider.createRemoteWatcher(ClusterActorRefProvider.scala:39)
	at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:186)
	at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:31)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:620)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:617)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:617)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:634)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
	at spark.jobserver.JobServer$.spark$jobserver$JobServer$$makeSupervisorSystem$1(JobServer.scala:154)
	at spark.jobserver.JobServer$$anonfun$main$1.apply(JobServer.scala:156)
	at spark.jobserver.JobServer$$anonfun$main$1.apply(JobServer.scala:156)
	at spark.jobserver.JobServer$.start(JobServer.scala:54)
	at spark.jobserver.JobServer$.main(JobServer.scala:156)
	at spark.jobserver.JobServer.main(JobServer.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by depend** [comment]
I linked with a wrong version of Spark. I just pushed a new image. Try now.

**Comment by endriju** [comment]
@depend it works perfectly now, thank you!

**Comment by depend** [comment]
@endriju good to know. are you running in mesos or standaone?

**Comment by vvsh** [comment]
@depend, I tried new image, but I still have the same exception:

java.lang.UnsatisfiedLinkError: /usr/lib/libmesos-1.0.0.so: libdb-4.7.so: cannot open shared object file: No such file or directory.

**Comment by depend** [comment]
@vvsh this is strange.  I can see the files under /usr/lib

> [root@456a1d3b2a24 /]# find /usr/lib -name libdb*
/usr/lib/libdb_cxx-4.7.so
/usr/lib/libdb-4.7.so
/usr/lib/db4.7.25/libdb_cxx.so
/usr/lib/db4.7.25/libdb.so
[root@456a1d3b2a24 /]#

**Comment by vvsh** [comment]
@depend, I also see the file there.

**Comment by depend** [comment]
@vvsh, what is your mesos version? I might need to use an older version like velvia/spark-jobserver.

**Comment by vvsh** [comment]
@depend, can you try to build it with mesos 0.28.2?

**Comment by vvsh** [comment]
@depend I see you have pushed the new image. Error disappeared. Thank you!

Now I have the same issue as I have had before when I built mesos myself with your image.

I am starting streaming application with such master: mesos://mesos-master:5050. After the start CPU usage increases on all containers (https://yadi.sk/i/P16gRDzL36uscM), after some time mesos master and slave loose their connections to zookeeper (it seems because docker network is overloaded) and master UI becomes unresponsive. Also, after some time my Apache Cassandra's container stops and at the same time mesos kills application's framework. Maybe my docker machine has small number of memory (6 GB), but it is pretty strange.

**Comment by depend** [comment]
@vvsh 
spark-2.0-preview.mesos-0.28.2.spark-2.0.2.scala-2.11.jdk-8-jdk is essentially the official image with new spark/mesos. Good to know that one works.

I also pushed another one: **spark-2.0-preview.mesos-0.28.2.spark-2.0.2.scala-2.11.jdk-8u112**. This one is based on CentOS. If you don't mind, can you test it with mesos as well?

About your issues, the box does seem to be overloaded. Maybe you can throttle you streaming application a bit to see if it makes any differences.

**Comment by vvsh** [comment]
@depend, it works perfectly in standalone mode and I can launch additional applications with different inputs.

**Comment by depend** [comment]
@vvsh, how about within mesos? I hope to just keep one image for standalone/mesos.

**Comment by vvsh** [comment]
@depend, I will try second images soon.

As for my issues, I uploaded logs, maybe they can help:
mesos-slave: https://drive.google.com/file/d/0B_Qdw-RQWjukTVpKMVJnblE3SVE/view?usp=sharing
mesos-master: https://drive.google.com/file/d/0B_Qdw-RQWjukeFNlR1VzaUxlMjQ/view?usp=sharing

**Comment by vvsh** [comment]
@depend, I tried, it works exactly as spark-2.0-preview.mesos-0.28.2.spark-2.0.2.scala-2.11.jdk-8-jdk.

**Comment by depend** [comment]
@vvsh, good to know. Maybe you can ask other folks about mesos. I only have limited experience with it.

**Comment by vvsh** [comment]
@depend, what place do you recommend for such question? Mesos or Spark mailing list?

**Comment by depend** [comment]
@vvsh, probably Mesos since it tries to kill the task. Maybe you can adjust logging to see the reason of killing. It's possible the cluster (single box) is out of resource and Mesos starts killing stuff.

**Comment by vvsh** [comment]
@depend, do you know how to specify memory for spark running in media?

**Comment by endriju** [comment]
@depend I'm running the image standalone.

**Comment by endriju** [comment]
Will there be docker image for SJS 0.7.0?

**Comment by velvia** [comment]
Yes, it will come out shortly.

**Comment by endriju** [comment]
@velvia Looking forward to it, thank you!

**Comment by endriju** [comment]
Just noticed there is SJS 0.7.0 at https://hub.docker.com/r/sparkjobserver/spark-jobserver/tags/

**Comment by velvia** [comment]
Yes.  Also spark2.0-preview has been merged to master.  We have to decide how to release the docker image for that.

**Comment by noorul** [comment]
We will be releasing 0.8.0 master, at that time container will be available.
