### ISSUE TITLE
Can not instantiate Kafka consumer with Spark Job Server

### ISSUE THREAD

**Issue by DanyangLinda** [spark-jobserver/spark-jobserver#911]
Hello,

This is a follow up issue to https://github.com/spark-jobserver/spark-jobserver/issues/900.
I have the same problem elaborated there. The original ticket was closed with a walkaround solution which is using spark-streaming-kafka-0-8. However we cannot use spark-streaming-kafka-0-8 because this version doesn't support TLS and we must have this security feature. 

The problem is when using spark jobserver (build from branch spark-2.0-preview) with spark-streaming-kafka-0-10_2.11-2.1.1, jobs will immediately fail with ClassNotFound Exception for org.apache.kafka.clients.consumer.RangeAssignor (More details in https://github.com/spark-jobserver/spark-jobserver/issues/900). Seems like driver process launched by Spark-Jobserver cannot find the class. 

We have tried to 
1. explicitly add spark-streaming-kafka-0-10_2.11-2.1.1 to spark driver classpath (not working, even if I could see the jar is there)

2. package spark-streaming-kafka-0-10_2.11-2.1.1 in fat jar (not working).

Interesting thing is Spark-submit works well with spark-streaming-kafka-0-10_2.11-2.1.1. We are keen to use Spark-Jobserver. But this issue is a blocker for us to go on with Spark-Jobserver

Thanks!

**Comment by noorul** [comment]
@DanyangLinda Can you try master branch?

**Comment by thoHeinze** [comment]
Your problems are not related to the Spark jobserver itself, but they are caused by a [problem](https://issues.apache.org/jira/browse/KAFKA-3680) with the 0.10 Kafka client. The Kafka library can not be dynamically loaded due to some problems with the class loader. 
These problems only occur inside the jobserver as he will load your JAR during runtime. In contrast, if you do a simple spark-submit no dynamic loading takes place. 
The problems have been fixed in Kafka 0.10.1 by [this patch](https://github.com/apache/kafka/pull/1421). However, the spark-streaming-kafka didn't update this dependency this quite a while. 

You can manually update the Kafka dependency to version where this problem has been fixed. In maven this would look like this: 
```
       <dependency>
               <groupId>org.apache.spark</groupId>
               <artifactId>spark-streaming-kafka-0-10_2.11</artifactId>
               <version>2.2.1</version>
               <scope>compile</scope>
               <exclusions>
                       <exclusion>
                               <groupId>org.apache.kafka</groupId>
                               <artifactId>kafka_2.11</artifactId>
                       </exclusion>
              </exclusions>
       </dependency>
       <dependency>
                <groupId>org.apache.kafka</groupId>
                <artifactId>kafka_2.11</artifactId>
                <version>0.10.2.1</version>
       </dependency>
```

Something similar should also work for sbt.

**Comment by bsikander** [comment]
Closing due to inactivity.

**Comment by tushar1032** [comment]
Hi has this issue been resolved as I am still facing it:
My Setup consists of: 
spark-job-server version 0.9.0
spark 2.3.2
kafka 0.10.0.1
spark-streaming-kafka-0-10_2.11 version 2.3.2

`ERROR .jobserver.JobManagerActor [] [akka://JobServer/user/jobManager-e44d5b3b-01da-4302-a42e-de2443f77a7f] - Got Throwable
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:702)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:557)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:540)
        at org.apache.spark.streaming.kafka010.Subscribe.onStart(ConsumerStrategy.scala:84)
        at org.apache.spark.streaming.kafka010.DirectKafkaInputDStream.consumer(DirectKafkaInputDStream.scala:70)
        at org.apache.spark.streaming.kafka010.DirectKafkaInputDStream.start(DirectKafkaInputDStream.scala:240)
        at org.apache.spark.streaming.DStreamGraph$$anonfun$start$7.apply(DStreamGraph.scala:54)
        at org.apache.spark.streaming.DStreamGraph$$anonfun$start$7.apply(DStreamGraph.scala:54)
        at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:143)
        at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:136)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
        at ... run in separate thread using org.apache.spark.util.ThreadUtils ... ()
        at org.apache.spark.streaming.StreamingContext.liftedTree1$1(StreamingContext.scala:578)
        at org.apache.spark.streaming.StreamingContext.start(StreamingContext.scala:572)
        at org.apache.spark.streaming.api.java.JavaStreamingContext.start(JavaStreamingContext.scala:556)
        at com.spmsoftware.distributed.test.Application.runJob(Application.java:70)
        at com.spmsoftware.distributed.test.Application.run(Application.java:77)
        at com.spmsoftware.distributed.test.Application.run(Application.java:29)
        at spark.jobserver.japi.JavaJob.runJob(JavaJob.scala:20)
        at spark.jobserver.japi.JavaJob.runJob(JavaJob.scala:11)
        at spark.jobserver.JobManagerActor$$anonfun$getJobFuture$4.apply(JobManagerActor.scala:594)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.clients.consumer.RangeAssignor ClassNotFoundException exception occured
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:227)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:637)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:557)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:540)
        at org.apache.spark.streaming.kafka010.Subscribe.onStart(ConsumerStrategy.scala:84)
        at org.apache.spark.streaming.kafka010.DirectKafkaInputDStream.consumer(DirectKafkaInputDStream.scala:70)
        at org.apache.spark.streaming.kafka010.DirectKafkaInputDStream.start(DirectKafkaInputDStream.scala:240)
        at org.apache.spark.streaming.DStreamGraph$$anonfun$start$7.apply(DStreamGraph.scala:54)
        at org.apache.spark.streaming.DStreamGraph$$anonfun$start$7.apply(DStreamGraph.scala:54)
        at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:143)
        at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:136)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.clients.consumer.RangeAssignor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:332)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:225)
        ... 23 more
`
